Controllers/ActorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MovieRex.Models;

namespace MovieRex.Controllers
{
    public class ActorController : BaseController
    {
        private readonly MovieRexDBContext _context;

        public ActorController(MovieRexDBContext context)
        {
            _context = context;
        }

        // GET: Actor
        public async Task<IActionResult> Index()
        {
            if (!IsLogin)
            {
                return RedirectToAction("Login", "Account");
            }
            if (CurrentUser == "admin")
            {
                return _context.Actors != null ?
                              View(await _context.Actors.ToListAsync()) :
                              Problem("Entity set 'MovieRexDBContext.Actors'  is null.");
            }
            return RedirectToAction("Index", "Home");
        }

        // GET: Actor/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (!IsLogin)
            {
                return RedirectToAction("Login", "Account");
            }
            if (CurrentUser == "admin")
            {
                if (id == null || _context.Actors == null)
                {
                    return NotFound();
                }

                var actor = await _context.Actors
                    .FirstOrDefaultAsync(m => m.ActorID == id);
                if (actor == null)
                {
                    return NotFound();
                }

                return View(actor);
            }
            return RedirectToAction("Index", "Home");
            
        }

        // GET: Actor/Create
        public IActionResult Create()
        {
            if (!IsLogin)
            {
                return RedirectToAction("Login", "Account");
            }
            if (CurrentUser == "admin")
            {
                return View();
            }
            return RedirectToAction("Index", "Home");
            
        }

        // POST: Actor/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ActorID,Name,Gender")] Actor actor)
        {
            if (ModelState.IsValid)
            {
                _context.Add(actor);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(actor);
        }

        // GET: Actor/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (!IsLogin)
            {
                return RedirectToAction("Login", "Account");
            }
            if (CurrentUser == "admin")
            {
                if (id == null || _context.Actors == null)
                {
                    return NotFound();
                }

                var actor = await _context.Actors.FindAsync(id);
                if (actor == null)
                {
                    return NotFound();
                }
                return View(actor);
            }
            return RedirectToAction("Index", "Home");            
        }

        // POST: Actor/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ActorID,Name,Gender")] Actor actor)
        {
            if (id != actor.ActorID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(actor);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ActorExists(actor.ActorID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(actor);
        }

        // GET: Actor/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (!IsLogin)
            {
                return RedirectToAction("Login", "Account");
            }
            if (CurrentUser == "admin")
            {
                if (id == null || _context.Actors == null)
                {
                    return NotFound();
                }

                var actor = await _context.Actors
                    .FirstOrDefaultAsync(m => m.ActorID == id);
                if (actor == null)
                {
                    return NotFound();
                }

                return View(actor);
            }
            return RedirectToAction("Index", "Home");            
        }

        // POST: Actor/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Actors == null)
            {
                return Problem("Entity set 'MovieRexDBContext.Actors'  is null.");
            }
            var actor = await _context.Actors.FindAsync(id);
            if (actor != null)
            {
                _context.Actors.Remove(actor);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ActorExists(int id)
        {
          return (_context.Actors?.Any(e => e.ActorID == id)).GetValueOrDefault();
        }
    }
}

Controllers/GenreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MovieRex.Models;

namespace MovieRex.Controllers
{
    public class GenreController : BaseController
    {
        private readonly MovieRexDBContext _context;

        public GenreController(MovieRexDBContext context)
        {
            _context = context;
        }

        // GET: Genre
        public async Task<IActionResult> Index()
        {
            if (!IsLogin)
            {
                return RedirectToAction("Login", "Account");
            }
            if (CurrentUser == "admin")
            {
                return _context.Genres != null ?
                          View(await _context.Genres.ToListAsync()) :
                          Problem("Entity set 'MovieRexDBContext.Genres'  is null.");
            }
            return RedirectToAction("Index", "Home");
            
        }

        // GET: Genre/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (!IsLogin)
            {
                return RedirectToAction("Login", "Account");
            }
            if (CurrentUser == "admin")
            {
                if (id == null || _context.Genres == null)
                {
                    return NotFound();
                }

                var genre = await _context.Genres
                    .FirstOrDefaultAsync(m => m.GenreID == id);
                if (genre == null)
                {
                    return NotFound();
                }

                return View(genre);
            }
            return RedirectToAction("Index", "Home");
            
        }

        // GET: Genre/Create
        public IActionResult Create()
        {
            if (!IsLogin)
            {
                return RedirectToAction("Login", "Account");
            }
            if (CurrentUser == "admin")
            {
                return View();
            }
            return RedirectToAction("Index", "Home");
            
        }

        // POST: Genre/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("GenreID,GenreTitle")] Genre genre)
        {
            if (ModelState.IsValid)
            {
                _context.Add(genre);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(genre);
        }

        // GET: Genre/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (!IsLogin)
            {
                return RedirectToAction("Login", "Account");
            }
            if (CurrentUser == "admin")
            {
                if (id == null || _context.Genres == null)
                {
                    return NotFound();
                }

                var genre = await _context.Genres.FindAsync(id);
                if (genre == null)
                {
                    return NotFound();
                }
                return View(genre);
            }
            return RedirectToAction("Index", "Home");            
        }

        // POST: Genre/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("GenreID,GenreTitle")] Genre genre)
        {
            if (id != genre.GenreID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(genre);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GenreExists(genre.GenreID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(genre);
        }

        // GET: Genre/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (!IsLogin)
            {
                return RedirectToAction("Login", "Account");
            }
            if (CurrentUser == "admin")
            {
                if (id == null || _context.Genres == null)
                {
                    return NotFound();
                }

                var genre = await _context.Genres
                    .FirstOrDefaultAsync(m => m.GenreID == id);
                if (genre == null)
                {
                    return NotFound();
                }

                return View(genre);
            }
            return RedirectToAction("Index", "Home");
            
        }

        // POST: Genre/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Genres == null)
            {
                return Problem("Entity set 'MovieRexDBContext.Genres'  is null.");
            }
            var genre = await _context.Genres.FindAsync(id);
            if (genre != null)
            {
                _context.Genres.Remove(genre);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool GenreExists(int id)
        {
          return (_context.Genres?.Any(e => e.GenreID == id)).GetValueOrDefault();
        }
    }
}

Controllers/MovieFavouriteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MovieRex.Models;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace MovieRex.Controllers
{
    public class MovieFavouriteController : BaseController
    {
        private readonly MovieRexDBContext _context;

        public MovieFavouriteController(MovieRexDBContext context)
        {
            _context = context;
        }
        // GET: /<controller>/
        public async Task<IActionResult> Index()
        {
            if (!IsLogin)
            {
                return RedirectToAction("Login", "Account");
            }
            var movieFavourite = _context.MovieFavourites.Where(m => m.UserName == CurrentUser).Include(m => m.Movie);            
            return View(await movieFavourite.ToListAsync());
        }
    }
}

Views/Shared/_Auth.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MovieRex</title>    
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/auth.css" asp-append-version="true" />
    <link rel="icon" href="/img/m.png" type="image/x-icon">
</head>
<body>
    <header>
        <nav class="nav navbar-expand-md sticky-top">
            <div class="container-fluid">
                <div class="logo" id="logo">
                    <a class="navbar-brand" href="#">
                        <img src="/img/movierex.png" height="100px" style="margin: -20px 0px;">
                    </a>
                </div>
            </div>
        </nav>

    </header>
    @RenderBody()

    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="~/js/auth.js" asp-append-version="true"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MovieRex</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/6.2.1/css/font-awesome.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MovieRex.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="/lib/Swiper/swiper-bundle.min.css">
    <link rel="icon" href="/img/m.png" type="image/x-icon">
</head>
<body>
    <header>
        <nav class="nav navbar-expand-md fixed-top">
            <div class="container-fluid">
                <div class="logo" id="logo">
                    <a class="navbar-brand" asp-controller="Home" asp-action="Index">
                        <img src="/img/movierex.png" height="100px" style="margin: -20px 0px;">
                    </a>
                </div>
                <!-- <button class="navber-toggler" type="button" data-toggle="collapse" data-target="#menu">
                    <span class="navbar-toggler-icon"></span>
                </button> -->
                <div class="container-fluid mt-3">
                    <button class="btn btn-dark d-lg-none" type="button" id="menu-button" data-bs-toggle="offcanvas" data-bs-target="#canva">
                        <ion-icon name="menu-outline" id="but-me"></ion-icon>
                    </button>
                    <div class="dropdown" id="dropdown">
                        <a class="btn dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            <img src="/img/icons8-user-25.png">
                        </a>
                        <ul class="dropdown-menu" id="dropdown-menu">
                            <li><a asp-controller="Account" asp-action="Details" asp-route-id="@ViewBag.UserName" class="dropdown-item" id="username">@ViewBag.UserName</a></li>
                            @if (ViewBag.UserName == "admin")
                            {
                                <li><a class="dropdown-item" asp-controller="Movie" asp-action="Index">Khu Vực Quản Trị</a></li>
                            }
                            else
                            {
                                <li><a class="dropdown-item">Tài Khoản</a></li>
                            }
                            <li><a class="dropdown-item" asp-controller="Account" asp-action="Logout">Đăng Xuất</a></li>
                        </ul>
                    </div>
                </div>
                <div class="collapse navbar-collapse " id="menu">
                    <ul class="navbar-nav my-2">
                        <li class="nav-item">
                            <a class="nav-link active" asp-controller="Home" asp-action="Index">Trang chủ</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Home" asp-action="Movie">Phim</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Home" asp-action="TV">Truyền Hình</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="MovieFavourite" asp-action="Index">Danh Sách Của Tôi</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

    </header>
    @RenderBody()

    <div class="footer">
        <div class="social">
            <a class="footer1" href="#"><ion-icon id="facebook" name="logo-facebook"></ion-icon></a>
            <a class="footer1" href="#"><ion-icon id="instagram" name="logo-instagram"></ion-icon></a>
            <a class="footer1" href="#"><ion-icon id="twitter" name="logo-twitter"></ion-icon></a>
            <a class="footer1" href="#"><ion-icon id="youtube" name="logo-youtube"></ion-icon></a>
        </div>
        <div id="footer2">
            <div class="row">
                <a class="col m-3" href="http://127.0.0.1:5500/User/Member.html">Đội ngũ thành lập</a>
                <a class="col m-3" href="#">Quan hệ với nhà đầu tư</a>
                <a class="col m-3" href="#">Thông báo pháp lý</a>
                <a class="col m-3" href="#">Trung tâm đa phương tiện</a>
            </div>
            <div class="row">
                <a class="col m-3" href="#">Trung tâm trợ giúp</a>
                <a class="col m-3" href="#">Việc làm</a>
                <a class="col m-3" href="#">Tùy chọn cookie</a>
                <a class="col m-3" href="#">Quyền riêng tư</a>
            </div>
            <div class="row">
                <a class="col m-3" href="#">Thẻ quà tặng</a>
                <a class="col m-3" href="#">Điều khoản sử dụng</a>
                <a class="col m-3" href="#">Thông tin doanh nghiệp</a>
                <a class="col m-3" href="#">Liên hệ với chúng tôi</a>
            </div>
        </div>
        <div style="text-align:left; padding: 0px 10px 10px 10px; margin-left: 100px;">
            <span style="font-size: 12px; font-weight: 100; color: gray;">© 2003-2022 MovieRex, Inc.</span>
        </div>
    </div>
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery/dist/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/swiper/swiper-bundle.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="/lib/Swiper/swiper-bundle.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_NewLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">
    <title>@ViewData["Title"] - MovieRex</title>
    <link rel="stylesheet" href="~/lib/bootstrap/bootstrap.min.css" />    
    <link rel="stylesheet" href="~/css/custom.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@300;400;500;700;900&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Material+Icons" rel="stylesheet">

</head>
<body>
    <div class="wrapper">
        <div class="body-overlay"></div>
        <!-- Sidebar  -->
        <nav id="sidebar">
            <div class="sidebar-header">
                <h3><img src="~/img/m.png" class="img-fluid w-10" /><span>MovieRex</span></h3>
            </div>
            <ul class="list-unstyled components">
                <li>
                    <a <a asp-controller="Account" asp-action="Index" class="dashboard"><i class="material-icons">account_circle</i><span>Account</span></a>
                </li>            
                <li class="dropdown">
                    <a href="#homeSubmenu1" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
                        <i class="material-icons">local_movies</i><span>Movie</span>
                    </a>
                    <ul class="collapse list-unstyled menu" id="homeSubmenu1">
                        <li>
                            <a asp-controller="Movie" asp-action="Index">Index</a>
                        </li>
                        <li>
                            <a asp-controller="Movie" asp-action="Create">Create</a>
                        </li>                        
                    </ul>
                </li>

                <li class="dropdown">
                    <a href="#pageSubmenu2" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
                        <i class="material-icons">recent_actors</i><span>Actor</span>
                    </a>
                    <ul class="collapse list-unstyled menu" id="pageSubmenu2">
                        <li>
                            <a asp-controller="Actor" asp-action="Index">Index</a>
                        </li>
                        <li>
                            <a asp-controller="Actor" asp-action="Create">Create</a>
                        </li>
                    </ul>
                </li>

                <li class="dropdown">
                    <a href="#pageSubmenu3" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
                        <i class="material-icons">category</i><span>Genre</span>                       
                    </a>
                    <ul class="collapse list-unstyled menu" id="pageSubmenu3">
                        <li>
                            <a asp-controller="Genre" asp-action="Index">Index</a>
                        </li>
                        <li>
                            <a asp-controller="Genre" asp-action="Create">Create</a>
                        </li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#pageSubmenu4" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
                        <i class="material-icons">smart_display</i><span>Cast</span>
                    </a>
                    <ul class="collapse list-unstyled menu" id="pageSubmenu4">
                        <li>
                            <a asp-controller="MovieActor" asp-action="Index">Index</a>
                        </li>
                        <li>
                            <a asp-controller="MovieActor" asp-action="Create">Create</a>
                        </li>
                    </ul>
                </li>

                <li class="dropdown">
                    <a href="#pageSubmenu5" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
                        <i class="material-icons">border_color</i><span>Movie Genre</span>
                    </a>
                    <ul class="collapse list-unstyled menu" id="pageSubmenu5">
                        <li>
                            <a asp-controller="MovieGenre" asp-action="Index">Index</a>
                        </li>
                        <li>
                            <a asp-controller="MovieGenre" asp-action="Create">Create</a>
                        </li>
                    </ul>
                </li>                
            </ul>
        </nav>


    <!-- Page Content  -->
        <div id="content">

            <div class="top-navbar">
                <nav class="navbar navbar-expand-lg">
                    <div class="container-fluid">

                        <button type="button" id="sidebarCollapse" class="d-xl-block d-lg-block d-md-mone d-none">
                            <span class="material-icons">arrow_back_ios</span>
                        </button>

                        <a class="navbar-brand" href="#"> Dashboard </a>

                        <button class="d-inline-block d-lg-none ml-auto more-button" type="button" data-toggle="collapse"
                                data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="material-icons">more_vert</span>
                        </button>

                        @*<div class="collapse navbar-collapse d-lg-block d-xl-block d-sm-none d-md-none d-none" id="navbarSupportedContent">
                        <ul class="nav navbar-nav ml-auto">
                            <li class="nav-item">
                                <a class="nav-link" href="#">
                                    <span class="material-icons">settings</span>
                                </a>
                            </li>
                        </ul>
                    </div>*@
                    </div>
                </nav>
            </div>

            <div>
                @RenderBody()
            </div>
            <footer class="footer">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-3">
                            <p class="copyright d-flex justify-content-end">
                                © 2003-2022 MovieRex, Inc.
                            </p>
                        </div>
                    </div>
                </div>
            </footer>
            <script src="~/lib/jquery/dist/jquery-3.3.1.slim.min.js"></script>
            <script src="~/lib/jquery/dist/popper.min.js"></script>
            <script src="~/lib/bootstrap/bootstrap.min.js"></script>
            <script src="~/lib/jquery/dist/jquery-3.3.1.min.js"></script>
            @await RenderSectionAsync("Scripts", required: false)
            <script type="text/javascript">$(document).ready(function () {
                    $('#sidebarCollapse').on('click', function () {
                        $('#sidebar').toggleClass('active');
                        $('#content').toggleClass('active');
                    });

                    $('.more-button,.body-overlay').on('click', function () {
                        $('#sidebar,.body-overlay').toggleClass('show-nav');
                    });

                });</script>
</body>
</html>